server:
  port: 8083
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    cache: false


  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1


file:
  path: C:/Temp/

user:
  data:
    uname: admin
    upwd: admin
