server:
  port: 8083
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    cache: false


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


file:
  path: E:\迅雷下载\

user:
  data:
    uname: admin
    upwd: admin
